### ISSUE TITLE
Using async without await in example

### ISSUE THREAD

**Issue by knownasilya** [tchak/ember-fetch-adapter#3]
I think you are missing an `await`, and then using that result and another `await` with the `json()`.

**Comment by tchak** [comment]
The adapter have a different api from a regular `fetch`. `adapter.fetch` returns a response proxy with body type methods on it: `json()`, `text()` etc. This makes for a nicer api. If you want access to raw fetch `Response` you can call `response()`. I know that I need to write more docs for this thing... Sorry about that.

**Comment by knownasilya** [comment]
Hum, then you shouldn't need `async` if not using `await` 👍

**Comment by tchak** [comment]
You right. Thank you. I fixed it.
